image:
  repository: ghcr.io/bullet-ant/canary-demo
  tag: "v3.2.0"
  pullPolicy: IfNotPresent

replicaCount: 3

port: 5000

stable:
  role: stable

canary:
  role: canary

prometheus:
  scrape: true

ingress:
  host: canary-demo.local
