apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stable
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-canary
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
